In [1]:
import pandas as pd
df = pd.read_csv(r'D:\datasets\MHassembly.csv')
df

,election_year,election_type,election_state,constituency,constituency_no,serial_no,candidate,party,evm_votes,postal_votes
0,2024,Assembly,MH,AKKALKUWA,1,1,AMSHYA FULJI PADVI,Shiv Sena,72411,218
1,2024,Assembly,MH,AKKALKUWA,1,2,ADV K C PADAVI,Indian National Congress,69122,603
2,2024,Assembly,MH,AKKALKUWA,1,3,PADMAKAR VIJAYSING VALVI,Bharat Adivasi Party,8640,192
3,2024,Assembly,MH,AKKALKUWA,1,4,ENG. JELSING BIJALA PAWARA,Independent,2895,16
4,2024,Assembly,MH,AKKALKUWA,1,5,SARYA DHARMA PADVI,Independent,1466,7
...,...,...,...,...,...,...,...,...,...,...
4419,2024,Assembly,MH,JAT,288,8,BHIMGONDA RAMGONDA BIRADAR,Independent,87,1
4420,2024,Assembly,MH,JAT,288,9,MAHADEV MURGYAPPA HUCHGOND,Independent,205,5
4421,2024,Assembly,MH,JAT,288,10,MAHADEO MEGHU PAWAR,Independent,339,2
4422,2024,Assembly,MH,JAT,288,11,LAXMAN GUNDA PUJARI,Independent,294,3
4423,2024,Assembly,MH,JAT,288,12,NOTA,None of the Above,1012,7

# Data Cleaning

In [3]:
#duplicates
df.duplicated().sum()

np.int64(0)

In [4]:
df.isnull().sum()

election_year      0
election_type      0
election_state     0
constituency       0
constituency_no    0
serial_no          0
candidate          0
party              0
evm_votes          0
postal_votes       0
dtype: int64

In [5]:
df.drop(columns = ['serial_no'], inplace = True)

In [6]:
df

,election_year,election_type,election_state,constituency,constituency_no,candidate,party,evm_votes,postal_votes
0,2024,Assembly,MH,AKKALKUWA,1,AMSHYA FULJI PADVI,Shiv Sena,72411,218
1,2024,Assembly,MH,AKKALKUWA,1,ADV K C PADAVI,Indian National Congress,69122,603
2,2024,Assembly,MH,AKKALKUWA,1,PADMAKAR VIJAYSING VALVI,Bharat Adivasi Party,8640,192
3,2024,Assembly,MH,AKKALKUWA,1,ENG. JELSING BIJALA PAWARA,Independent,2895,16
4,2024,Assembly,MH,AKKALKUWA,1,SARYA DHARMA PADVI,Independent,1466,7
...,...,...,...,...,...,...,...,...,...
4419,2024,Assembly,MH,JAT,288,BHIMGONDA RAMGONDA BIRADAR,Independent,87,1
4420,2024,Assembly,MH,JAT,288,MAHADEV MURGYAPPA HUCHGOND,Independent,205,5
4421,2024,Assembly,MH,JAT,288,MAHADEO MEGHU PAWAR,Independent,339,2
4422,2024,Assembly,MH,JAT,288,LAXMAN GUNDA PUJARI,Independent,294,3
4423,2024,Assembly,MH,JAT,288,NOTA,None of the Above,1012,7

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   election_year    4424 non-null   int64
 1   election_type    4424 non-null   object
 2   election_state   4424 non-null   object
 3   constituency     4424 non-null   object
 4   constituency_no  4424 non-null   int64
 5   candidate        4424 non-null   object
 6   party            4424 non-null   object
 7   evm_votes        4424 non-null   int64
 8   postal_votes     4424 non-null   int64
dtypes: int64(4), object(5)
memory usage: 311.2+ KB

In [9]:
df.info

<bound method DataFrame.info of       election_year election_type election_state constituency  \
0              2024      Assembly             MH    AKKALKUWA
1              2024      Assembly             MH    AKKALKUWA
2              2024      Assembly             MH    AKKALKUWA
3              2024      Assembly             MH    AKKALKUWA
4              2024      Assembly             MH    AKKALKUWA
...             ...           ...            ...          ...
4419           2024      Assembly             MH          JAT
4420           2024      Assembly             MH          JAT
4421           2024      Assembly             MH          JAT
4422           2024      Assembly             MH          JAT
4423           2024      Assembly             MH          JAT

      constituency_no                   candidate                     party  \
0                   1          AMSHYA FULJI PADVI                 Shiv Sena
1                   1              ADV K C PADAVI  Indian National Congress
2                   1    PADMAKAR VIJAYSING VALVI      Bharat Adivasi Party
3                   1  ENG. JELSING BIJALA PAWARA               Independent
4                   1          SARYA DHARMA PADVI               Independent
...               ...                         ...                       ...
4419              288  BHIMGONDA RAMGONDA BIRADAR               Independent
4420              288  MAHADEV MURGYAPPA HUCHGOND               Independent
4421              288         MAHADEO MEGHU PAWAR               Independent
4422              288         LAXMAN GUNDA PUJARI               Independent
4423              288                        NOTA         None of the Above

      evm_votes  postal_votes
0         72411           218
1         69122           603
2          8640           192
3          2895            16
4          1466             7
...         ...           ...
4419         87             1
4420        205             5
4421        339             2
4422        294             3
4423       1012             7

[4424 rows x 9 columns]>

In [10]:
df.shape

(4424, 9)

In [12]:
df.to_csv('Accident_data')

In [13]:
pwd

'C:\\Users\\Karan'